### ISSUE TITLE
Add support for puya sourcemaps to `avm-debugger`

### ISSUE THREAD

**Issue by aorumbayev** [algorandfoundation/algokit-avm-vscode-debugger#32]
## Description

In order to support puya breakpoint debugging, `avm-debugger` needs to be updated to support puya sourcemaps.

## Technical Details

* `avm-debugger` implementation is updated to support `op` state scopes.
* Consider source unavailable scenarios (e.g. 3rd party code, synthetic code), and how best to present that to the user (DAP should have a standard way of communicating this) -> NON ISSUE revalidate 

## Acceptance Criteria

* A dap session can be initiated by supplying a) avm trace file b) puya sourcemaps. 
* During debug session, the baseline set of features must match the TEAL debugging experience.

## Tasks

- [x]  - Local variable (python) resolution, validate edge cases for scenarios when debugging contracts with both teal and puya sourcemaps available. Local variables for TEAL should not have local variable section, Puya should show additional puya specific information + local variables section in place @aorumbayev  + add example of a puya contract with 3rd party lib imports
-  - [x] - Evaluate if watch mode support is useful in avm debug adapter 
- [x] - Providing a structure to describe the type for particular variables 
- [ ] - Expanding the 'evaluate' for 'Locals' section variable  in the extension to allow decoding avm values (feature parity for what TEAL already provides, bytes -> a) hex b) base64 c) utf8 d) raw byte array 
- [x] - Validate DAP resolves relative paths in source artifacts @aorumbayev
